name: Android CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write  # 允许发布release
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Build JAR with Gradle
      run: |
        echo 'org.gradle.caching=true' >> gradle.properties
        echo 'org.gradle.parallel=true' >> gradle.properties
        echo 'org.gradle.vfs.watch=true' >> gradle.properties
        echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
        ./gradlew clean jar
        ./gradlew --stop
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword }}

    - name: Find built JAR
      id: jar
      run: |
        JAR_PATH=$(find . -type f -name "*.jar" | grep -v "sources\|javadoc" | head -n 1)
        echo "jar_path=$JAR_PATH" >> $GITHUB_OUTPUT

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifact
        path: ${{ steps.jar.outputs.jar_path }}
        if-no-files-found: error

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.jar.outputs.jar_path }}
        tag_name: ${{ github.ref_name }}-jar-$(date +%Y%m%d%H%M%S)
        name: "Release JAR - ${{ github.ref_name }}"
        body: "自动构建的JAR包，可直接下载。"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
